:toc:
:numbered:

== Day01: es6 Warm Up & 객체 협력 모델
ifndef::imagesdir:[:imagesdir: .]

=== ES6

* Symbol()
* async / await
** async 는 전파된다.
** 동기/비동기 로직이 사라진다.
** 지역 변수에 대한 접근이 가능하다.
* destructuring

https://youtu.be/LB3OvN8ctso?list=PLBNdLLaRx_rLzsln__WwoOuGwt0ZnAmS5&t=3566

=== Exam01: 통으로 짜여진 소스

link:{imagesdir}/exam01.html[]

[plantuml, exam01_class, png]
....
class Table {
    - htmlTagId: String
    + constructor(htmlTagId: String): Table
    + load(uri: String): Void
    - _render(): Void
}
....

[plantuml, exam01_sequence, png]
....
actor client
participant table <<Table>>

client -> table: constructor(htmlTagId: String): Table
activate table
return table

client -> table: load(uri: String): Void
activate table
table -> table: _render(): Void
....

* 문제: [red]#SRP 위배# - 단일 책임 클래스가 아니다.
*** load 메서드와 render 메소드가 한 클래스에 있어 응집도가 낮다.

=== Exam02: SRP 적용

* 책임, 역할, 협력 모데 구축
** 책임을 갖는 역활에 따라 객체 협력 모델 작성

WARNING: private 을 Symbol() 처리해야 하지만 이후는 편의 상 _ 로 대신 처

link:{imagesdir}/exam02.html[]

[plantuml, exam02_class, png]
....
@startuml
class DataSupplier {
    - _uri: String
    + constructor(uri: String): DataSupplier
    + getInfo(): String
}

class Renderer {
    + _info: String
    - _htmlTagId: String
    + constructor(htmlTagId: String): Renderer
    + render(dataSupplier: DataSupplier): Void
    - _render(): Void
}

DataSupplier - Renderer
@enduml
....

[plantuml, exam02_sequence, png]
....
actor client
participant dataSupplier <<DataSupplier>>
participant renderer <<Renderer>>

client -> dataSupplier: constructor(uri: String): DataSupplier
activate dataSupplier
return dataSupplier

client -> renderer: constructor(htmlTagId: String): Renderer
activate renderer
return renderer

client -> renderer: render(dataSupplier: DataSupplier): Void
activate renderer
dataSupplier <- renderer : getInfo(): String
dataSupplier --> renderer: json: String
renderer -> renderer: _render(): Void
....

* 문제: [red]#OOP 위배# - 객체 간의 통신에 값을 사용하고 있다.
** 값(JSON)으로 통신하기 때문에 정합성을 보장할 수 없다.
** [red]#객체 간의 통신은 정합성을 스스로 보장하는 타입으로 통신# 해야 한다.

* 참고: [red]#함수형은 값으로만 통신해야 한다.#

=== Exam03: OOP 요건 적용

link:{imagesdir}/exam03.html[]

* OOP 에서 객체 간의 통신
** 값이 아닌 #정합성을 스스로 보장하는 타입# 을 주고 받아야 한다.

[plantuml, exam03_class, png]
....
@startuml
class Info {
    - title: String
    - header: String
    - items: String
    + constructor(json: String): Info
    + getTitle(): String
    + getHeader(): String
    + getItems(): String
}

class DataSupplier {
    - _uri: String
    + constructor(uri: String): DataSupplier
    + getInfo(): Info
}

class Renderer {
    + _info: Info
    - _htmlTagId: String
    + constructor(htmlTagId: String): Renderer
    + render(dataSupplier: DataSupplier): Void
    - _render(): Void
}

Info -- DataSupplier
Info -- Renderer
DataSupplier - Renderer
@enduml
....

[plantuml, exam03_sequence, png]
....
actor client
participant dataSupplier <<DataSupplier>>
participant renderer <<Renderer>>

client -> dataSupplier: constructor(uri: String): DataSupplier
activate dataSupplier
return dataSupplier

client -> renderer: constructor(htmlTagId: String): Renderer
activate renderer
return renderer

client -> renderer: render(dataSupplier: DataSupplier): Void
activate renderer
dataSupplier <- renderer: getInfo(): String
activate dataSupplier
dataSupplier --> renderer: json: String
renderer -> renderer: _render(): Void
....

* 문제: [red]#OCP 위배# - 도메인 모델과 네이티브 모델이 분할 되어 있지 않다.
** 네이티브에 사정에 의해 변화가 이미 작성된 코드를 수정해야 한다.
** 처리기가 늘어날 때마다 기존 코드를 수정해서 분기 처리해야 한다.

=== Exam04: OCP 적용

link:{imagesdir}/exam04.html[]

* 도메인 객체와 네이티브 객체 분리
** Template Method Pattern

[plantuml, exam04_class, png]
....
@startuml
class Info {
    - title
    - header
    - items
    + constructor(json)
    + getTitle()
    + getHeader()
    + getItems()
}

abstract class DataSupplier {
    + getInfo() : Info
    - {abstract} _getData()
}

class JsonDataSupplier {
    - _uri: String
    + constructor(uri)
    - _getData()
}

abstract class Renderer {
    + _info: Info
    + render(dataSupplier: DataSupplier)
    - {abstract} _render()
}

class TableRenderer {
    - _htmlTagId
    + constructor(htmlTagId: String)
    - {abstract} _render()
}

class ConsoleRenderer {
    + constructor()
    - {abstract} _render()
}

Info -- DataSupplier
Info -- Renderer
DataSupplier <|-- JsonDataSupplier
DataSupplier <|-- XMLDataSupplier
DataSupplier - Renderer
Renderer <|-- TableRenderer
Renderer <|-- ConsoleRenderer
@enduml
....

[plantuml, exam04_sequence, png]
....
actor client
participant dataSupplier <<JsonDataSupplier>>
participant renderer <<TableRenderer>>

client -> dataSupplier: constructor(uri: String): JsonDataSupplier
activate dataSupplier
return dataSupplier

client -> renderer: constructor(htmlTagId: String): TableRenderer
activate renderer
return renderer

client -> renderer: render(dataSupplier: DataSupplier): Void
activate renderer
dataSupplier <- renderer: getInfo(): Info
activate dataSupplier
dataSupplier -> dataSupplier: _getData(): Void
dataSupplier --> renderer: info: Info
deactivate dataSupplier
renderer -> renderer: _render(): Void
....
