:toc:
:numbered:

== Day02: 디자인 패턴
ifndef::imagesdir:[:imagesdir: .]

=== 객체 지향 언어의 필수 요건

* 대체 가능성
** LSP
* 내적 일관성(동질성)
** Overriding

link:{imagesdir}/index01.html[]

=== Design Pattern Category: 구.행.성

태양계 - 9행성: 수금지화목토천해명

* 구조패턴
* 행동패턴
* 생성패턴

=== 객체 지향 설계를 학습할 수 있는 분류

* 변화율
* 캡슐화
* 다형성
* 역활 모델
* 객체 관계
* ...

=== #상태에 대한 분기는 사라지지 않는다.#

그 분기가 필요해서 태어났기 때문이다.

.하지만 정의 시점에 제거하는 방법은 있다.
* 분기 수 만큼 객체를 만들고
* 실행 시점에 경우의 수를 공급한다.

=== 분기를 실행 시점으로 옮길 때의 장단점

.장점: 일정한 통제 범위 내에서 확장 가능한 알고리즘 설계 가능
* 정의 시점에 모든 경우를 몰라도 됨
* 정의 시점에 그 경우를 처리하는 방법도 몰라도 됨
* 예: 게임 초기에 향후 모든 무기를 고래햐지 않아도 된다.

.단점: 매 호스트 코드마다 안정성을 따로 담보해야 함
* 실행 시점에 모든 경우를 반드시 기술해야 함
* 실행 시점마다 알고리즘의 안정성을 담보해야 함

.단점 극복 패턴: 패턴은 패턴으로 안정성을 답보해야 한다.
* Factory Pattern
* Builder Pattern

=== 제어문 기반의 알고림즘이 갖는 문제

* 수정하면 전체가 검파일 됨
* #알고리즘이 변화한 부분만 수정하고 나머지는 건드리고 싶지 않다면?#
** 방법 1: 최대한 개별 알고리즘을 함수로 추출한다. (프로시저 지향 -절차 지향)
*** 해결 안 된 문제: 경우가 변경될 때
*** 해결 안 된 문제: 공통 의존 데이터 문제
**** 상태에 대한 의존성이 여러 함수에 걸쳐 나타난다.
** 방법 2: 상태의 상태를 사용하는 기능의 캡슐화 (객체 지향)
*** 상속 위임
*** 소유 위임

=== 객체 지향에서 알고리즘 분화 시 선택할 수 있는 두 가지 방법

==== 상속 위임

is a (kind of)

==== 소유 위임

has a

=== 속도와 메모리는 바꿀 수 있다.

성능과 저장 공간은 바꿀 수 있다.

=== 함수는 값이다.

* 식은 값이다.
* 함수는 식이다.
* #함수는 값이다.#
* #메모리와 연산는 상호교환 가능하다.#

디자인 패턴은 연산을 많이 쓰는 방식으로 발전했다.
메모리가 귀할 때 나온 것이기 때문이다.
게임 업계에서는 속도를 높이기 위해 연산보다 메모리를 많이 사용하는 쪽으로 발젆했다.
따라서 게임에서는 디자인 패턴을 거의 적용하지 않는다.

=== 디자인 패턴의 2번째 원리

문으로 구성하면 다시 컴파일해야 하는 문제를 없애기 위해 문을 제거해서 값(식)으로 바꿀 수 있는 객체화 시키기

=== if 를 제거하기 위한 패턴

* Template Method Pattern
* Strategy Pattern
* State Pattern

=== loop 를 제거하기 위한 패턴

* Iterator Pattern
* Composite Pattern
* Visitor Pattern

=== loop 이후 if 를 제거하기 위한 패턴 (예: sum, every)

* Decorator Pattern
* Chain Of Responsiblity Pattern

=== 절차적인 부분을 값으로 하고 싶을 때

* Command Pattern
* Mediator Pattern

=== 여러 개의 객체들의 조립해야 할 때

* Builder Pattern
* Facade Pattern

=== Template Method Pattern - 상속 위임

link:{imagesdir}/templateMethodPattern02.html[]

[plantuml, templateMethodPattern_class, png]
.....
Github <|-- ImageLoader
Github <|-- MdLoader
Global <-- MdLoader

class Global {
    {static} d64: Function
}

class Github {
    - {static} _callbackId: int
    - {static} callback: Function
    - _githubUriTemplate: String
    + constructor(userId: String, githubRepoName: String): GitHub
    + load(path: String): Void
    - {abstract} _loaded(content: String): Void
}

class ImageLoader {
    - _jsonpScript: HtmlTag
    + constructor(userId: String, repoName: String, jsonpScript: HtmlTag)
    - _loaded(content: String): Void
}

class MdLoader {
    - _jsonpScript: HtmlTag
    + constructor(userId: String, githubRepoName: String, jsonpScript: HtmlTag)
    - _loaded(content: String): Void
    - _parseMD(content: String): Void
}
.....

[plantuml, templateMethodPattern_sequence, png]
.....
actor client
participant s75img <<ImageLoader>>
participant s75md <<MdLoader>>

client -> s75img: constructor(userId, githubRepoName, jsonpScript): ImageLoader
activate s75img
return s75img

client -> s75img: load(path): Void
activate s75img
    s75img -> s75img: _load(content): Void
    activate s75img
    deactivate s75img
deactivate s75img

client -> s75md: constructor(userId, githubRepoName, jsonpScript): ImageLoader
activate s75md
return s75md

client -> s75md: load(path): Void
activate s75md
    s75md -> s75md: _load(content): Void
    activate s75md
        s75md -> s75md: _parseMD(content): Void
        activate s75md
            s75md -> Global: d64(content: String): String
            activate Global
            s75md <- Global: decodeURIComponent: String
            deactivate Global
        deactivate s75md
    deactivate s75md
deactivate s75md
.....

=== Strategy Pattern - 소유 위임

Template Method Pattern 과 Strategy Pattern 반드시 1:1 교환할 수 있다.

link:{imagesdir}/strategyPattern03.html[]

[plantuml, strategyPattern_class, png]
.....
class Global {
    {static} d64: Function
    {static} parseMD(content: String): String
    {static} getHtmlTagUsingHtmlTagId: HtmlTag
    {static} imgParser: Function
    {static} mdParser: Function
}

class Github {
    - {static} _callbackId: int
    - {static} callback: Function
    - _githubUriTemplate: String
    + constructor(userId: String, githubRepoName: String): GitHub
    + load(path: String): Void
    + parser(parser: Function): Setter
}
.....

[plantuml, strategyPattern_sequence, png]
.....
actor client

client -> github: constructor(userId, githubRepoName): Github
activate github
return github

client -> github: parser(imgParser): Setter
activate github
deactivate github

client -> github: load(path): Void
activate github
deactivate github

client -> github: parser(mdParser): Setter
activate github
deactivate github

client -> github: load(path): Void
activate github
deactivate github
.....

=== Command Pattern

전략 패턴의 발전형

* Command 객체
** 함수와 그 함수가 사용하는 인자들을 묶어서 하나의 커맨드 객체로 만들어 저장

* Command Pattern 구성 요소
** Command 객체
** Invoker

link:{imagesdir}/commandPattern04.html[]

[plantuml, commandPattern_class, png]
.....
Github -> Command

class Global {
    {static} d64: Function
    {static} parseMD(content: String): String
    {static} getHtmlTagUsingHtmlTagId: HtmlTag
    {static} imgParser: Function
    {static} mdParser: Function
}

class Github {
    - {static} _callbackId: int
    - {static} callback: Function
    - _githubUriTemplate: String
    - _command: Command
    + constructor(userId: String, githubRepoName: String): GitHub
    + load(path: String): Void
    + command(command: Command): Setter
}

class Command {
    - _parser: Function
    - _args: Array
    + constructor(parser: Function, args: Array)
    + parser: Getter
    + args: Getter
}
.....

[plantuml, commandPattern_sequence, png]
.....
actor client
participant gitHub <<Github>>
participant imgCommand <<Command>>
participant mdCommand <<Command>>

client -> gitHub: constructor(userId: String, githubRepoName: String): Github
activate gitHub
return gitHub

client -> imgCommand: constructor(imgParser: Function, args: Array): Command
activate imgCommand
return imgCommand

client -> gitHub: command(imgCommand: Command): Setter
activate gitHub
deactivate gitHub

client -> gitHub: load(path): Void
activate gitHub
deactivate gitHub

client -> mdCommand: constructor(mdParser: Function, args: Array): Command
activate mdCommand
return mdCommand

client -> gitHub: command(mdCommand: Command): Setter
activate gitHub
deactivate gitHub

client -> gitHub: load(path): Void
activate gitHub
deactivate gitHub
.....

=== Router

모든 경우의 수를 알 수 있다면, 경우와 그 해결책을 테이블에 저장할 수 있다.

발생 가능한 경우의 수를 값으로 기술한다.

* Router 의 구성 요소
** Routing Table: Map<경우, 해결책>

link:{imagesdir}/router05.html[]

[plantuml, router_class, png]
.....
Github -> Command
Loader -> Command
Loader -> Github

class Global {
    {static} d64: Function
    {static} parseMD(content: String): String
    {static} getHtmlTagUsingHtmlTagId: HtmlTag
    {static} imgParser: Function
    {static} mdParser: Function
}

class Github {
    - {static} _callbackId: int
    - {static} callback: Function
    - _githubUriTemplate: String
    - _command: Command
    + constructor(userId: String, githubRepoName: String): GitHub
    + load(path: String): Void
    + command(command: Command): Setter
}

class Command {
    - _parser: Function
    - _args: Array
    + constructor(parser: Function, args: Array)
    + parser: Getter
    + args: Getter
}

class Loader {
    - _github: Github
    - _router: Map
    + constructor(userId: String, githubRepoName: String): Loader
    + add(ext: String, command: Command): Void
    + load(path: String): Void
}
.....

[plantuml, router_sequence, png]
.....
actor client
participant loader <<Loader>>
participant github <<Github>>
participant imgCommand <<Command>>
participant mdCommand <<Command>>

client -> loader: constructor(userId: String, githubRepoName: String): Loader
activate loader
    loader -> github: constructor(userId: String, githubRepoName: String): GitHub
    activate github
    loader <- github: gitHub: GitHub
    deactivate github
return loader

client -> imgCommand: constructor(imgParser: Function, args: Array): Command
activate imgCommand
return imgCommand

client -> loader: add(ext: String, imgCommand: Command
activate loader
deactivate loader

client -> loader: load(path: String): Void
activate loader
    loader -> github: command(command: Command): Setter
    activate github
    deactivate github
    loader -> github: load(path: String): Void
    activate github
        github -> imgCommand: parser(content: String, args: Array): Void
        activate imgCommand
        deactivate imgCommand
    deactivate github
deactivate loader

client -> mdCommand: constructor(mdParser: Function, args: Array): Command
activate mdCommand
return mdCommand

client -> loader: add(ext: String, mdCommand: Command): Void
activate loader
deactivate loader

client -> loader: load(path: String): Void
activate loader
    loader -> github: command(command: Command): Setter
    activate github
    deactivate github
    loader -> github: load(path: String): Void
    activate github
        github -> mdCommand: parser(content: String, args: Array): Void
        activate mdCommand
        deactivate mdCommand
    deactivate github
deactivate loader
.....